### ISSUE TITLE
Api nie przepuszcza "darmowych" requestów

### ISSUE THREAD

**Issue by przemekbok** [seszele64/docer-downloader#1]
Cześć, wygląda na to że api już nie przepuszcza zwykłych strzałów, podejrzewam że po obsłużeniu płatności generowany jest jakiś parametr ciasteczek i na jego podstawie wydawany jest url do pliku.

![image](https://github.com/seszele64/docer-downloader/assets/34289616/5b1248c6-e027-48ef-8d39-9844acba6281)

Jest opcja uzyskania linku prosto z drzewa DOM:
![image](https://github.com/seszele64/docer-downloader/assets/34289616/a337ef29-2306-4daa-810e-4854ab46150b)
![image](https://github.com/seszele64/docer-downloader/assets/34289616/0df5e0fc-9ee3-49bc-991a-8d87a6f61ec4)

**Comment by seszele64** [comment]
Tak, bardzo możliwe, bo wartość rc w requestach zrobiła się bardzo długa zamiast jak poprzednio losowej liczby 1-9.

Problem póki co rozwiązany przez zmianę mechanizmu działania z wysyłania requestów na fetchowanie z kodu źródłowego.

Dzięki za poruszenie tematu.
