### ISSUE TITLE
Wersja na Firefox

### ISSUE THREAD

**Issue by Letus252** [seszele64/docer-downloader#11]
Czy mógłbyś zrobić wersje na Firefoxa? Przydałaby się zwłaszcza biorąc pod uwage zbliżający się [ManifestV3](https://developer.chrome.com/docs/extensions/develop/migrate).

**Comment by seszele64** [comment]
Słuszna uwaga, siadam teraz i zobaczę co jestem w stanie wykminić

**Comment by seszele64** [comment]
Hej, generalnie to addon jest zgodny z manifest v3, robiłem zmianę jakiś czas temu, bo na starym nie działały mi pewne funkcje. W każdym razie udało mi się przerobić kod, żeby dodatek działał też na firefox, ale muszę jeszcze zbudować plik `.xpi`, żeby śmigało, postaram się to zrobić do końca dnia, bo muszę usiąść na innym komputerze.

**Comment by Letus252** [comment]
Nawet jeśli addon jest zgodny, ublock & adblock raczej nie.. Dzięki za odpowiedź!

**Comment by seszele64** [comment]
Hej, daję update. Póki co nie wrzucam wersji na firefoxa, bo mozilla i web-ext krzyczy mi, że mam jakieś błędy, i szczerze mam gdzieś dopicowywanie kodu tylko pod ich widzimisię.

**Comment by seszele64** [comment]
Lukniesz czy Ci śmiga? Będę wdzięczny!

https://addons.mozilla.org/en-US/firefox/addon/docer-downloader/

**Comment by Letus252** [comment]
Sprawdziłem działa na docer. Jeden tylko szczegół, mógłbyś zawężyć dostęp wtyczki tylko do strony docer? Nie żebym Cie o cokolwiek podejrzewał, jednak to zawsze lepiej jak wtyczka do yt ma dostęp tylko do yt, wtyczka do githuba tylko do githuba itd. Ps może doci support w przyszłości?

**Comment by seszele64** [comment]
Siema, dzieki za response, zaweze jak costam bedzie do robienia w kodzie poza tym. Chyba zostawiłem, po dodawaniu innych wersji stronki.

Masz na mysli zeby wtyczka dzialala na doci.pl ?

**Comment by Letus252** [comment]
Tak 👍
