### ISSUE TITLE
Rozszerzenie pozwala na pobieranie jedynie plikow PDF

### ISSUE THREAD

**Issue by areksobiczewski** [seszele64/docer-downloader#2]
Jak w tytule. Pliki PDF sa pobierane bez problemu.
Natomiast nie jest mozliwe pobranie zadnego innego rodzaju pliku...

To o tyle istotne, ze serwis Docer stal sie swego rodzaju przyczolkiem dla dostepnosci polskich ebookow (w formatach: epub, mobi, rtf i innych), ktorych prozno szukac gdzie indziej.

Odnosze wrazenie, ze plugin w jakis sposob wspolpracuje z mechanizmem podgladu dokumentow na stronie Docer. W takim razie daje znac, ze dla przytoczonych przeze mnie wyzej formatow plikow takie podglady rowniez sa przez strone generowane.

Co jest mozliwe w kwestii udostepnienia mozliwosci sciagania plikow innych niz PDF?

**Comment by seszele64** [comment]
Rozumiem, jak testowałem kod to pliki mobi i epub dało się ściągać tą samą metodą. Możesz podać linki do plików które nie działają?

**Comment by seszele64** [comment]
Okej, faktycznie kod nie działał dla innych rodzajów plików ze względu na inny DOM dla plików o rozszerzeniu innym niż .pdf i .epub

Dodałem możliwość ściągania plików niepdfowych (.mobi, .rtf) na podstawie mechanizmu ściągania .pdf-ów tylko z innym selektorem,

dodałem możliwość ściągania .epub na podstawie requesta get, który śmiga w tle (po zweryfikowaniu captcha)

**Comment by areksobiczewski** [comment]
To ja bardzo dziekuje Ci, @seszele64, ze znalazles sposob na "problem" jaki objawil nam sie sie na portalu Docer. Po czym zmaterializowales swoj pomysl do rozwiazania (ja np. zupelnie nie wpadlem na to jak przechwycic ten plik koncowy!), ktore od wczorajszej wersji 1.21. dziala idealnie :-) Nie mowiac juz o szybkosci z jaka zareagowales na moj request, bo to jest mistrzostwo swiata. Przybijam piatke!
Wszystko przetestowalem i zadowolony sciagnalem potrzebne mi rzeczy.

To moze jeszcze nie jest dla Ciebie oczywiste, ale Twoj plugin bedzie bardzo popularny.
To dlatego, ze cale podziemie ksiazkowe od wielu lat przechowywalo rozne unikalne pliki na portalach Docer i doci.pl. Okolo miesiac temu, po wielu latach bezproblemowej pracy, oba portale na raz wprowadzily bardzo srogi paywall, zostawiajac tym samym kilknanascie tysiecy osob z reka w nocniku. Te "dyski na pliki" byly na tyle dobre i bezproblemowe, ze odebraly rynek portalom takim jak Chomikuj, czy innym warezom. Zostalismy wiec zakladnikami naszej wlasnej glupoty i tzw. vendor lock-in.
Tu nie chodzi nawet o piractwo. Jest mnostwo pozycji ksiazkowych, ktorych po prostu nie da sie dostac na rynku. Dostep do nich to wazna sprawa, chocby dla ludzi pracujacych w srodowiskach naukowych.
No wiec problem z Docerem i Doci istnieje dopiero od 3,5 tygodnia. Wygladalo na to, ze przyjdzie nam sie poddac i przelknac gorzka porazke. A tu taka mila niespodzianka! Zupelnie przypadkiem przegladajac wykop.pl dowiedzialem sie o Twoim pluginie!
Narazie bardzo malo osob wie o jego istnieniu, ale to sie zmieni, bo potrzeba jest oczywista.
To, ze poczyniles takie narzedzie daje szanse: 1) normalnego korzystania z Docer-a do czasu wymyslenia jak zareagowac na te cala sytuacje; 2) otwiera droge do mozliwosci zaplanowania masowego przeniesienia danych na inne serwisy.

PS: Dla portalu doci.pl (ktory wydaje sie blizniaczym do Docer-a - widac ten sam paywall) aktualnie dzialajacym "rozwiazaniem" jest zalozenie sobie konta. Bedac zalogowanym nie obowiazuja limity platnego transferu plikow (jeszcze...). Na Docer nie ma takiej mozliwosci.
Jednakowoz, jesli znazalzbys chwile, moze zechcialbys sie przyjrzec mechanizmowi dzialania doci.pl i moze wprowadzic i obsluge tego portalu do swojego pluginu? Mam przeczucie, ze to moze zadzialac i z pewnoscia byloby mile widziane.

PS2: Twoje rozszerzenie dziala dobrze rowniez na przegladarce Chromium. Mozna dodac taka informacje w dokumentacji.

Z pewnoscia bedziemy sie jeszcze komunikowac, a ja bede tu czestym bywalcem.
Jesli moge jakos pomoc (backend, serwery, hakerskie cuda, angielski), dawaj znac!
W miedzyczasie, jesli bede mial jakies pomysly, bede zakladal nowe watki tutaj na githubie.

Jeszcze raz dzieki Ci dobry czlowieku :-) Az wraca mi wiara w czlowieka (i w IT), a serce rosnie :-) Pozdroweczki!
