### ISSUE TITLE
Wtyczka nie pobiera plików .pdf

### ISSUE THREAD

**Issue by uniexwasbanned** [seszele64/docer-downloader#3]
Nie ściąga po zweryfikowaniu CAPTCHA

Sprawdzane na Edge i Ungoogled Chromium.

Z plikami .epub nie ma niajmiejszych problemów, innych typów nie sprawdzałem.

**Comment by seszele64** [comment]
która wersja rozszerzenia?
jaki link dokumentu?

**Comment by foxto-blue** [comment]
Niektóre pliki pdf (na przykład /doc/8c0ss1c) pobierają się z pod innego url, konkretnie getpdf a nie pdf_dummy.
Wrzuciłem PR na to:  https://github.com/seszele64/docer-downloader/pull/4/files

**Comment by seszele64** [comment]
Zrobiłem merge twoich zmian, dzięki jeszcze raz,
@uniexwasbanned daj znać, czy dalej ci nie działa

**Comment by seszele64** [comment]
super, w takim razie zamykam temat

**Comment by seszele64** [comment]
jaka wersja rozszerzenia?
jaka przeglądarka?

**Comment by audiovoice** [comment]
Próbowałem w chrome i edge. Być może docer ma jakiś problem bo po kliknięciu w captcha plik nie ładuje się. Nie ma podglądu tego pdfa. Zauważyłem, że Twoja wtyczka nie ma problemu z pobieraniem plików pod warunkiem, że po kliknięciu w captcha wyświetla się podgląd.

**Comment by seszele64** [comment]
Tak, dokładnie tak działa wtyczka, inny mechanizm działania wymaga wiele innych permissions i przemodelowania sposobu działania wtyczki, póki co jesteś jedynym głosem o niedziałającej wtyczce

**Comment by audiovoice** [comment]
No to pobierz tego pdfa z linku i będzie jasne, że tylko mnie nie działa.

**Comment by seszele64** [comment]
Nieprecyzyjnie się wyraziłem, ten plik nie działa, ale na razie nie będę przerabiał kodu, ponieważ nie dostaję sygnałów, żeby problem dotyczył większej ilości plików.

**Comment by joarize** [comment]
siemka, wtyczka nie pobiera tego pliku: 
https://docer.pl/doc/8ve0vc1
sprawdzalem na chrome i operze gx
reszte plików pobiera bez zarzutu
