### ISSUE TITLE
doci.pl support

### ISSUE THREAD

**Issue by darth-aragoth** [seszele64/docer-downloader#5]
Hi, can you add please doci.pl service support?

**Comment by seszele64** [comment]
Hi, i will consider my options for implementing it within next two days, if it's possible I will let you know and implement it. Thank you for the idea!

**Comment by seszele64** [comment]
For now it's unfeasible to introduce doci.pl support due to few facts:
- downloads are possible when logged in
- idk if it's temporary, but downloads were also available when i tested it for non logged in users
- site works a bit differently
