### ISSUE TITLE
docer.com.ar

### ISSUE THREAD

**Issue by Gatienzo** [seszele64/docer-downloader#6]
Hi. Can you please make it work for docer.com.ar?

**Comment by seszele64** [comment]
Yes, I will try to integrate it within next 2 days.

**Comment by christian39** [comment]
Thank you!!!
While you are at it, can you do it also for docer.ar? Not sure about the difference with .com.ar though. They seem to be different sites.

**Comment by seszele64** [comment]
Working on it, i would say i'm half finished, want to introduce new system so that other potential sites will be also easier to add. Hoping for your patience :crossed_fingers:

**Comment by seszele64** [comment]
Hey guys, i updated the code, docer.com.ar and docer.ar should be working now.

Check it
https://github.com/seszele64/docer-downloader/archive/refs/heads/main.zip 
and let me know

**Comment by seszele64** [comment]
I integrated it into newest release 

https://github.com/seszele64/docer-downloader/releases/tag/1.23

**Comment by christian39** [comment]
Thank you! It worked like a charm!
