### ISSUE TITLE
Doci.pl support

### ISSUE THREAD

**Issue by szyjankowski** [seszele64/docer-downloader#8]
Hey, I love your work, but maybe there is way to extend its funcionality.

I believe docer.pl and doci.pl are similar code sites, so and doci.pl has the same kind of payment wall, which I believe funcions the same one as docer.pl. 

Maybe there is way to include it to the extension?

**Comment by seszele64** [comment]
please read:
https://github.com/seszele64/docer-downloader/issues/5
